[2021-01-11 16:20:58] local.ERROR: No Database connection yet in VoyagerServiceProvider loadAuth()  
[2021-01-11 20:02:40] local.INFO: [{"id":28,"task_name":"admin_test","task_ticket":"1234","start_date":"01\/07\/2021","end_date":"01\/07\/2021","status":"En cours","author":"member","folder_dir":"test"},{"id":15,"task_name":"nice","task_ticket":"1","start_date":"01\/15\/2021","end_date":"01\/21\/2021","status":"En cours","author":"test","folder_dir":"4"},{"id":12,"task_name":"current Task","task_ticket":"12324","start_date":"01\/07\/2021","end_date":"01\/07\/2021","status":"En cours","author":"test","folder_dir":"3"}]  
